import type { PulsoProspect } from "./prospects";

export const pulsoProspects31to40: PulsoProspect[] = [
  {
    id: "ana-studio-031",
    slug: "ana-studio",
    name: "ANA Studio",
    contactFirstName: "Ana y Yender",
    title: "esto es lo que vi en ANA Studio.",
    intro: "ANA Studio ya coordina diseño, materiales y ejecución para familias, builders y developers. Seguí el recorrido público pensando en cuánto contexto tiene que pasar de una etapa a otra antes de que un proyecto llegue a instalación.",
    facts: [
      {
        title: "Un solo contrato reúne muchos oficios y decisiones.",
        body: "La empresa publica que maneja pintura, pisos, drywall, gabinetes, vanities y suministro de materiales bajo un solo contrato. También reporta más de 100 proyectos completados en Orlando.",
        sources: [{ label: "Revisar ANA Studio", url: "https://www.linkedin.com/company/ana-studio-residential-design/" }],
      },
      {
        title: "El mismo equipo atiende proyectos para empresas y familias.",
        body: "ANA Studio se presenta como subcontractor para builders, developers y real estate, y también trabaja renovaciones completas para familias. Son recorridos distintos que pueden requerir datos, tiempos y responsables distintos.",
        sources: [{ label: "Ver el perfil público de ANA Studio", url: "https://www.linkedin.com/company/ana-studio-residential-design/" }],
      },
    ],
    unknowns: "Desconozco cómo pasa hoy la información desde la primera consulta hasta el alcance, el estimado, las selecciones de materiales y el calendario. Tampoco puedo afirmar que exista trabajo duplicado o pérdida de contexto.",
    review: "Mediríamos origen del proyecto, tipo de cliente, alcance, selecciones, estimado, aprobación, compras, calendario y siguiente acción. Así sabríamos qué parte ya fluye bien y dónde vale la pena conectar pasos. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo cómo viaja el contexto desde la primera consulta hasta la instalación, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "third-coat-032",
    slug: "third-coat",
    name: "Third Coat LLC",
    contactFirstName: "Darwin",
    title: "esto es lo que vi en Third Coat.",
    intro: "Me llamó la atención que Third Coat haya crecido alrededor de un trato muy directo contigo. Revisé el recorrido público pensando en todo lo que pasa entre una consulta, un estimado y un proyecto ya en marcha.",
    facts: [
      {
        title: "La operación pública deja mucho del recorrido directamente en tus manos.",
        body: "En la historia de Third Coat explicas que cada estimado, cada plan de proyecto y cada conversación con clientes pasa directamente por ti. También dices que no trabajas con un equipo de ventas ni un call center.",
        sources: [{ label: "Revisar la historia de Third Coat", url: "https://thirdcoat.com/about-us/" }],
      },
      {
        title: "El negocio atiende trabajos residenciales y comerciales.",
        body: "Third Coat publica servicios de pintura residencial, pintura comercial y cabinet refinishing. Cada tipo de trabajo puede traer datos, visitas, materiales, aprobaciones y tiempos distintos antes de empezar.",
        sources: [{ label: "Ver Third Coat", url: "https://thirdcoat.com/" }],
      },
    ],
    unknowns: "Desconozco cuánto tiempo te toma hoy mover datos entre consulta, visita, estimado, aprobación y calendario, y si la información ya queda unida sin tener que repetirla.",
    review: "Mediríamos fuente, tipo de proyecto, visita, estimado, aprobación, calendario, materiales y siguiente paso. La meta sería comprobar qué tareas dependen de ti y cuáles pueden pasar solas entre las herramientas que ya usas. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido completo sin cambiar lo que ya funciona, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "sumtek-shoes-033",
    slug: "sumtek-shoes-usa",
    name: "Sumtek Shoes USA",
    contactFirstName: "Jairo",
    title: "esto es lo que vi en Sumtek Shoes.",
    intro: "Me llamó la atención que Sumtek naciera de una necesidad que conocías de cerca desde Punto Fijo y la industria. Seguí el recorrido público pensando en cómo se mueve un pedido desde una empresa hasta la entrega final.",
    facts: [
      {
        title: "Sumtek combina atención individual con cuentas corporativas.",
        body: "La historia publicada por Ascendus describe ventas en tienda y entregas directas a empleados de cuentas corporativas, además de relaciones con 14 marcas de calzado de seguridad.",
        sources: [{ label: "Leer la historia de Sumtek", url: "https://www.ascendus.org/es/client-stories/jairo-rada/" }],
      },
      {
        title: "Los pedidos grandes tienen una dinámica distinta.",
        body: "Ascendus explica que los pedidos corporativos grandes son una parte importante del negocio y que requieren comprar inventario a proveedores antes de cobrar el pedido completo.",
        sources: [{ label: "Comprobar la historia en Ascendus", url: "https://www.ascendus.org/es/client-stories/jairo-rada/" }],
      },
    ],
    unknowns: "Desconozco cómo se gestionan hoy las solicitudes de cada empresa, tallas y modelos, disponibilidad, orden de compra, pago y entrega. También desconozco qué parte ya está conectada entre sistemas.",
    review: "Mediríamos empresa, contacto, modelos y tallas, disponibilidad, cotización, orden de compra, pago, entrega y seguimiento. Así sabríamos dónde se repite información y qué pasos pueden avanzar sin trabajo manual. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido de una cuenta corporativa desde la solicitud hasta la entrega, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "eco-green-auto-parts-034",
    slug: "eco-green-auto-parts",
    name: "ECO Green Auto Parts",
    contactFirstName: "Carlos",
    title: "esto es lo que vi en ECO Green Auto Parts.",
    intro: "ECO Green mueve piezas, cotizaciones y entregas en un negocio donde cada solicitud necesita bastante contexto. Revisé las rutas públicas que usa una persona o empresa cuando quiere pedir una pieza.",
    facts: [
      {
        title: "El formulario de cotización ya recoge varios datos útiles.",
        body: "La web pide nombre, correo, teléfono, empresa, dirección de entrega y permite adjuntar archivos. Eso da una buena base para que la solicitud llegue con contexto desde el inicio.",
        sources: [{ label: "Revisar ECO Green Auto Parts", url: "https://ecogautoparts.com/" }],
      },
      {
        title: "WhatsApp aparece como otra ruta de contacto.",
        body: "El sitio también invita a escribir por WhatsApp. Son dos puertas válidas para una misma intención: conseguir disponibilidad, precio y entrega de una pieza.",
        sources: [{ label: "Ver las rutas de contacto", url: "https://ecogautoparts.com/" }],
      },
    ],
    unknowns: "Desconozco si formulario, WhatsApp y llamadas terminan en un mismo registro del pedido, y si datos como vehículo, pieza, disponibilidad, precio y entrega viajan juntos hasta cerrar la venta.",
    review: "Mediríamos canal de entrada, vehículo o pieza, disponibilidad, cotización, dirección, pago, preparación, entrega y seguimiento. Así se puede comprobar dónde el equipo mueve información a mano y dónde ya fluye sola. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo cómo se mueve una solicitud desde el primer mensaje hasta la entrega, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "maintenance-team-solutions-035",
    slug: "maintenance-team-solutions",
    name: "Maintenance Team Solutions",
    contactFirstName: "Milagros",
    title: "esto es lo que vi en Maintenance Team Solutions.",
    intro: "MTS opera dos líneas muy distintas bajo una misma empresa: limpieza comercial y reparación mecánica. Revisé cómo se presenta cada una y qué datos necesita una solicitud para llegar al equipo correcto.",
    facts: [
      {
        title: "Las dos divisiones publican contactos distintos.",
        body: "La web separa Janitorial & Construction Cleanup de Mechanical Repair y publica teléfono y correo propios para cada división.",
        sources: [{ label: "Revisar Maintenance Team Solutions", url: "https://www.mtsorlando.com/" }],
      },
      {
        title: "La operación cubre varios estados y tipos de cliente.",
        body: "MTS publica servicio en Florida, Georgia y Alabama. La parte de limpieza atiende distintos tipos de instalaciones y la división mecánica trabaja con motores, transmisiones, diésel, botes y RVs.",
        sources: [{ label: "Ver servicios y cobertura", url: "https://www.mtsorlando.com/" }],
      },
    ],
    unknowns: "Desconozco cómo se clasifica hoy cada solicitud, qué datos recibe la persona que la toma y si una cuenta que usa más de una división conserva el mismo historial y contexto.",
    review: "Mediríamos división, ubicación, tipo de activo o instalación, prioridad, primera respuesta, responsable, trabajo programado y siguiente acción. Así sabríamos si cada solicitud llega completa al equipo correcto. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo cómo viaja una solicitud entre entrada, asignación y trabajo terminado, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "venelegal-036",
    slug: "venelegal",
    name: "VENELEGAL",
    contactFirstName: "Vicente",
    title: "esto es lo que vi en VENELEGAL.",
    intro: "VENELEGAL conecta una operación entre Orlando y Caracas y atiende varios tipos de trámite para personas y empresas. Seguí el recorrido público pensando en cuánto contexto necesita cada caso antes de llegar a la persona correcta.",
    facts: [
      {
        title: "La firma trabaja con equipo y presencia en Estados Unidos y Venezuela.",
        body: "La web presenta oficinas en Orlando y Caracas y un equipo que atiende asuntos legales, migratorios, comerciales y documentales.",
        sources: [{ label: "Revisar VENELEGAL", url: "https://venelegal.com/" }],
      },
      {
        title: "El catálogo público reúne muchos tipos de servicio.",
        body: "VENELEGAL publica trámites migratorios, visas, permisos, asilo, traducciones certificadas, apostillas, notarías y otros servicios. Cada uno exige datos, documentos, fechas y responsables distintos.",
        sources: [{ label: "Revisar los servicios", url: "https://venelegal.com/servicios/" }],
      },
    ],
    unknowns: "Desconozco cómo entra hoy cada consulta, cómo se clasifica por servicio y jurisdicción, y cómo se mantiene visible qué documento falta, quién lleva el caso y cuál es la siguiente acción.",
    review: "Mediríamos origen, tipo de servicio, jurisdicción, documentos pendientes, responsable, fecha clave, primera respuesta y siguiente acción. La meta sería comprobar que el contexto acompaña al cliente sin depender de búsquedas o traspasos manuales. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido desde la primera consulta hasta el siguiente paso del caso, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "rgc-builders-037",
    slug: "rgc-builders",
    name: "R.G.C Builders I LLC",
    contactFirstName: "Roberth",
    title: "esto es lo que vi en R.G.C Builders.",
    intro: "R.G.C Builders coordina varias etapas que normalmente viven en manos distintas: diseño, ingeniería, permisos, presupuesto y construcción. Revisé el recorrido público pensando en cómo pasa la información de una etapa a la siguiente.",
    facts: [
      {
        title: "La empresa publica un recorrido de proyecto con varias disciplinas.",
        body: "La página de servicios incluye arquitectura, ingeniería, permitting, construction, project management e inspections/compliance, además de trabajos residenciales y comerciales.",
        sources: [{ label: "Revisar servicios de R.G.C Builders", url: "https://rgcbuilders1.com/services/" }],
      },
      {
        title: "La web promete respuesta a cada solicitud dentro de 24 horas.",
        body: "En la página About se publica el compromiso de responder cada request dentro de 24 horas. Esa promesa se puede medir desde el primer contacto hasta que el proyecto queda bien clasificado.",
        sources: [{ label: "Revisar About", url: "https://rgcbuilders1.com/about/" }],
      },
    ],
    unknowns: "Desconozco cómo se conectan hoy consulta, alcance, presupuesto, diseño, permiso y calendario, y si el equipo debe volver a pedir datos que ya llegaron en una etapa anterior.",
    review: "Mediríamos origen, tipo de proyecto, propiedad, etapa, alcance, presupuesto, permiso, responsable, primera respuesta y siguiente acción. Así se puede ver qué traspasos ya funcionan y cuáles consumen tiempo del equipo. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo cómo pasa un proyecto desde la consulta hasta la ejecución, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "pa-paraguana-038",
    slug: "pa-paraguana",
    name: "Pa' Paraguaná",
    contactFirstName: "July y Néstor",
    title: "esto es lo que vi en Pa' Paraguaná.",
    intro: "Me llamó la atención que hayan llevado el nombre de su península al negocio y que la operación ya tenga dos puntos. Revisé cómo se reparten públicamente los pedidos entre ubicación y canal.",
    facts: [
      {
        title: "La web ya muestra dos ubicaciones con rutas de pedido propias.",
        body: "Pa' Paraguaná publica un punto en Kissimmee y otro en Orlando, con teléfonos y accesos para ordenar según la ubicación.",
        sources: [{ label: "Revisar Pa' Paraguaná", url: "https://www.paparaguana.com/" }],
      },
      {
        title: "Los pedidos también llegan por varios canales.",
        body: "El sitio ofrece pickup y delivery y enlaza servicios externos de entrega. El menú además reúne decenas de sabores de empanadas y otros productos.",
        sources: [{ label: "Ver pedidos y menú", url: "https://www.paparaguana.com/" }],
      },
    ],
    unknowns: "Desconozco cómo se unen hoy ubicación, canal, pedido, disponibilidad e incidencia cuando una orden entra por vías distintas, y cuánto trabajo requiere mantener todo alineado.",
    review: "Mediríamos ubicación, canal, tipo de pedido, disponibilidad, preparación, entrega o pickup, incidencia y resultado. Así se puede comprobar qué datos ya viajan bien entre canales y dónde el equipo tiene que intervenir a mano. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido de un pedido desde que entra hasta que se entrega, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "sofrito-latin-cafe-039",
    slug: "sofrito-latin-cafe",
    name: "Sofrito Latin Cafe",
    contactFirstName: "Maria",
    title: "esto es lo que vi en Sofrito Latin Cafe.",
    intro: "Sofrito lleva años operando y hoy combina restaurante, pedidos y eventos. Revisé esas rutas públicas pensando en qué información necesita cada una antes de quedar confirmada.",
    facts: [
      {
        title: "La operación pública tiene varios tipos de pedido.",
        body: "La web ofrece dine-in, pickup y delivery, además de catering y eventos privados. Son intenciones distintas que terminan usando parte del mismo equipo y calendario.",
        sources: [{ label: "Revisar Sofrito Latin Cafe", url: "https://www.sofritocafe.com/" }],
      },
      {
        title: "Catering tiene un recorrido propio.",
        body: "La sección de catering permite pedir una cotización y también ordenar, con opciones de pickup, delivery y distintos niveles de servicio.",
        sources: [{ label: "Revisar Catering", url: "https://www.sofritocafe.com/catering" }],
      },
    ],
    unknowns: "Desconozco cómo se conectan hoy una consulta de evento, una cotización, la fecha, el número de invitados, la confirmación y la operación del día. Tampoco puedo ver cuánto seguimiento se hace a mano.",
    review: "Mediríamos canal, tipo de solicitud, fecha, invitados, cotización, confirmación, responsable y siguiente acción. Así sabríamos dónde el contexto ya se conserva y dónde conviene conectar pasos. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido desde una consulta de catering hasta un evento confirmado, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "al-renovations-040",
    slug: "al-renovations",
    name: "A&L Renovations LLC",
    contactFirstName: "Daymari y José",
    title: "esto es lo que vi en A&L Renovations.",
    intro: "Me llamó la atención la historia de A&L: dos venezolanos, una de Yaracuy y otro de Lara, construyendo una empresa de remodelación en Orlando. Revisé el recorrido público que empieza cuando alguien pide un estimado.",
    facts: [
      {
        title: "La empresa cubre varias etapas y oficios dentro de una remodelación.",
        body: "A&L publica servicios de remodelación, reparación y rehabilitación, además de trabajos como pisos. En flooring, la misma ruta puede incluir visita, muestras, medición, selección e instalación.",
        sources: [{ label: "Revisar A&L Renovations", url: "https://alrenovationsllc.com/about-us/" }, { label: "Ver Flooring Installation", url: "https://alrenovationsllc.com/flooring-installation/" }],
      },
      {
        title: "El primer paso público es pedir un estimado.",
        body: "La web invita a programar un Free Estimate para que un profesional lleve muestras, mida el espacio y ayude a escoger materiales antes de instalar.",
        sources: [{ label: "Revisar el recorrido de estimado", url: "https://alrenovationsllc.com/flooring-installation/" }],
      },
    ],
    unknowns: "Desconozco cómo pasa hoy la información desde el primer contacto hasta visita, medidas, materiales, estimado, aprobación y calendario, y si algún dato se vuelve a pedir o copiar.",
    review: "Mediríamos fuente, tipo de proyecto, visita, medidas, selección, estimado, aprobación, materiales, calendario y siguiente acción. Así sabríamos qué parte ya fluye sola y dónde se consume tiempo moviendo contexto. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieren revisar conmigo cómo pasa un proyecto desde el primer estimado hasta la instalación, escríbanme.",
    ctaEvent: "pulso_cta_call",
  },
];
