import type { PulsoProspect } from "./prospects";

export const pulsoProspects21to30: PulsoProspect[] = [
  {
    id: "capella-immigration-021",
    slug: "capella-immigration-law",
    name: "Capella Immigration Law",
    contactFirstName: "Camila",
    title: "esto es lo que vi en Capella Immigration Law.",
    intro: "Capella ya tiene una experiencia real en español y explica con claridad varios procesos de inmigración. Seguí el recorrido público de una persona que pasa de informarse a intentar pedir una cita.",
    facts: [
      {
        title: "El botón para pedir una cita merece una comprobación directa.",
        body: "Durante la auditoría del sitio, el botón “Book Your Appointment” aparecía en varias páginas sin llevar a una ruta de reserva. Es un punto importante porque aparece cuando la persona ya tiene alta intención de hablar con el despacho.",
        sources: [{ label: "Revisar el sitio de Capella", url: "https://capellaimmigration.com/" }],
      },
      {
        title: "La experiencia en español ya está construida.",
        body: "El sitio ofrece contenido real en español para distintas áreas de práctica. Eso permite medir por separado qué temas, páginas e idioma terminan generando una consulta real.",
        sources: [{ label: "Ver Capella Immigration Law", url: "https://capellaimmigration.com/" }],
      },
    ],
    unknowns: "Desconozco si el botón ya fue corregido desde la auditoría, cuántas personas lo usan y cómo se registra hoy el origen de cada consulta. Tampoco puedo afirmar que se haya perdido un cliente por ese punto.",
    review: "Mediríamos página de origen, idioma, intención, inicio de contacto, primera respuesta, responsable y siguiente acción. Así sabríamos qué recorrido ya funciona y dónde conviene intervenir. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido desde que una persona llega al sitio hasta que queda lista para hablar con el despacho, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "immigration-universe-022",
    slug: "immigration-universe-attorneys",
    name: "Immigration Universe Attorneys",
    contactFirstName: "Ileana",
    title: "esto es lo que vi en Immigration Universe Attorneys.",
    intro: "La experiencia en español está integrada de verdad en Immigration Universe: sitio, contenido y educación para la comunidad latina. Seguí el recorrido público de una persona que decide pasar de informarse a pedir ayuda.",
    facts: [
      {
        title: "Una página en español todavía mostraba partes de plantilla y contenido en inglés.",
        body: "En la auditoría de la ruta pública en español aparecían secciones del FAQ en inglés y texto de plantilla. Es un detalle visible dentro de una experiencia que, en el resto del sitio, está muy bien adaptada al español.",
        sources: [{ label: "Revisar Immigration Universe", url: "https://immigration-uni.com/" }],
      },
      {
        title: "Había dos accesos públicos distintos al portal de MyCase.",
        body: "Durante la revisión aparecieron dos rutas públicas hacia el portal del cliente. Pueden responder a una transición válida. La pregunta útil es cuál debe usar hoy una persona y cómo queda conectada con su caso desde el primer contacto.",
        sources: [{ label: "Revisar el sitio oficial", url: "https://immigration-uni.com/" }],
      },
    ],
    unknowns: "Desconozco qué portal usa hoy el equipo como ruta principal, si las páginas ya fueron ajustadas y cómo se conecta el primer contacto con el intake y el seguimiento del caso.",
    review: "Mediríamos origen, idioma, tipo de consulta, portal utilizado, primera respuesta y siguiente paso. La meta sería comprobar que el contexto acompaña a la persona desde el contenido hasta el intake. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido completo, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "city-driving-school-023",
    slug: "city-driving-school",
    name: "City Driving School",
    contactFirstName: "Damir",
    title: "esto es lo que vi en City Driving School.",
    intro: "City Driving School ya ofrece atención en español y publica una vía específica para esa comunidad. Seguí el recorrido de una persona que intenta pasar de leer la información a registrarse.",
    facts: [
      {
        title: "La ruta de registro en español mostró errores durante la auditoría.",
        body: "Varios botones “Registrarte” de la versión en español llevaban a páginas que devolvían error, mientras el recorrido en inglés utilizaba otra ruta de registro. Ese punto ocurre justo antes de que un visitante se convierta en alumno.",
      },
      {
        title: "La atención en español ya tiene un canal propio.",
        body: "El negocio publica atención en español y un teléfono dedicado. Eso crea una base clara para medir cuántas consultas llegan por idioma y cuántas terminan en registro.",
      },
    ],
    unknowns: "Desconozco si las rutas de registro ya fueron corregidas, cuántas personas usan cada idioma y cómo se retoma a quien empieza el proceso y no lo termina.",
    review: "Mediríamos idioma, página de entrada, inicio de registro, error o abandono, contacto posterior y registro completado. Así se puede corregir solo lo que los datos justifiquen. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido desde la web hasta la inscripción, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "kissimmee-notary-024",
    slug: "kissimmee-notary-public",
    name: "Kissimmee Notary Public",
    contactFirstName: "Fatimah",
    title: "esto es lo que vi en Kissimmee Notary Public.",
    intro: "Kissimmee Notary Public tiene una reputación pública fuerte y también ofrece atención en español. Revisé qué encuentra una persona cuando pasa de conocer esa reputación a intentar reservar.",
    facts: [
      {
        title: "La sección de reseñas del propio sitio aparece sin contenido.",
        body: "Fuera de la página existe una presencia fuerte de opiniones de clientes. Dentro del sitio, esa prueba social no acompaña al visitante en el momento de decidir.",
        sources: [{ label: "Revisar Kissimmee Notary Public", url: "https://kissimmeenotarypublic.com/" }],
      },
      {
        title: "“Book Now” lleva a una solicitud en vez de mostrar horarios disponibles.",
        body: "El recorrido público permite dejar datos para pedir el servicio. La pregunta operativa es qué ocurre entre esa solicitud y la cita confirmada, y cuánto seguimiento requiere cada una.",
        sources: [{ label: "Revisar el sitio oficial", url: "https://kissimmeenotarypublic.com/" }],
      },
    ],
    unknowns: "Desconozco cuántas solicitudes entran, cuánto tarda la primera respuesta y qué parte del seguimiento ya ocurre de forma automática.",
    review: "Mediríamos fuente, servicio solicitado, idioma, hora de entrada, primera respuesta, cita confirmada y resultado. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido desde la solicitud hasta la cita, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "garay-eye-care-025",
    slug: "garay-eye-care",
    name: "Garay Eye Care",
    contactFirstName: "Leslie",
    title: "esto es lo que vi en Garay Eye Care.",
    intro: "Garay Eye Care coordina dos sedes en Orlando y la práctica tiene una ventaja real: tú hablas español con fluidez. Revisé cómo se refleja eso en el recorrido de una persona que intenta pedir una consulta.",
    facts: [
      {
        title: "“Schedule Your Consultation” lleva a un formulario general.",
        body: "El formulario pide nombre, correo, teléfono y comentarios, sin elegir sede, doctora ni horario. Baldwin Park y MetroWest además publican horarios distintos.",
        sources: [{ label: "Revisar Contacto", url: "https://www.garayeye.com/contact/" }],
      },
      {
        title: "La práctica tiene capacidad real de atender en español, pero el sitio no ofrece esa ruta.",
        body: "Tu dominio del español está documentado públicamente. En la auditoría del sitio no apareció una versión en español ni un selector de idioma.",
        sources: [{ label: "Revisar Garay Eye Care", url: "https://www.garayeye.com/" }],
      },
    ],
    unknowns: "Desconozco cómo se asigna hoy cada formulario por sede, doctora o idioma y cuántas solicitudes llegan de pacientes que prefieren español.",
    review: "Mediríamos fuente, idioma, sede, motivo de consulta, primera respuesta, cita confirmada y seguimiento. Así sabríamos qué parte necesita ajuste y qué parte ya funciona bien. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido entre las dos sedes y el primer contacto, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "mrs-busy-bee-026",
    slug: "mrs-busy-bee-air-conditioning",
    name: "Mrs. Busy Bee Air Conditioning and Heating",
    contactFirstName: "Esther",
    title: "esto es lo que vi en Mrs. Busy Bee.",
    intro: "Mrs. Busy Bee deja claro desde su presencia pública que atiende en español. Seguí el recorrido de una persona que busca servicio y decide cómo contactar al equipo.",
    facts: [
      {
        title: "El mismo sitio publica dos números de teléfono distintos.",
        body: "Durante la revisión aparecieron 407-715-0400 y 321-442-4992 en distintas zonas del sitio. Pueden cumplir funciones diferentes; lo importante es saber si ambos conservan el origen y el contexto de cada solicitud.",
        sources: [{ label: "Revisar Mrs. Busy Bee", url: "https://mrsbusybeefl.com/" }],
      },
      {
        title: "El español ya forma parte de la promesa pública.",
        body: "El sitio declara atención en español. Eso permite medir el recorrido por idioma desde el primer contacto hasta la visita o servicio confirmado.",
        sources: [{ label: "Ver el sitio oficial", url: "https://mrsbusybeefl.com/" }],
      },
    ],
    unknowns: "Desconozco si los dos números responden a campañas, áreas o equipos distintos y si terminan en un mismo registro del cliente.",
    review: "Mediríamos número o canal de entrada, fuente, idioma, tipo de servicio, primera respuesta, cita y resultado. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo cómo llega y se mueve cada solicitud antes de convertirse en trabajo, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "cleanair-contractors-027",
    slug: "cleanair-contractors-usa",
    name: "CleanAir Contractors USA",
    contactFirstName: "Yarinell",
    title: "esto es lo que vi en CleanAir Contractors USA.",
    intro: "CleanAir tiene capacidad bilingüe y una propuesta clara para clientes de Central Florida. Seguí el recorrido público de una persona que intenta contactar al negocio desde el sitio.",
    facts: [
      {
        title: "La página de contacto todavía muestra datos de otra empresa y otro estado.",
        body: "Durante la auditoría aparecían “James & Doug”, una dirección en Foxboro, Massachusetts, y un teléfono con código 617. El número real de CleanAir aparecía en otra zona del sitio.",
        sources: [{ label: "Revisar CleanAir Contractors", url: "https://cleanaircontractorsusa.godaddysites.com/contact-us" }],
      },
      {
        title: "El error está justo en la ruta donde alguien intenta pedir ayuda.",
        body: "El visitante puede llegar con intención alta y encontrarse con datos que no corresponden a CleanAir. Desde afuera se puede comprobar la publicación; el impacto real necesita medición.",
        sources: [{ label: "Ver el sitio oficial", url: "https://cleanaircontractorsusa.godaddysites.com/" }],
      },
    ],
    unknowns: "Desconozco cuánto tráfico llega a esa página, cuántas personas intentan usar esos datos y cómo se registra después cada solicitud real.",
    review: "Mediríamos página de origen, clic o llamada, servicio solicitado, primera respuesta y cita o visita confirmada. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido completo del primer contacto, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "legacy-fencing-028",
    slug: "legacy-fencing-corp",
    name: "Legacy Fencing Corp",
    contactFirstName: "Larry",
    title: "esto es lo que vi en Legacy Fencing.",
    intro: "Legacy Fencing tiene algo valioso: sus reseñas destacan la rapidez de respuesta y el sitio declara atención completa en inglés y español. Revisé cómo se presenta esa promesa en el primer contacto.",
    facts: [
      {
        title: "La misma página publica horarios que se contradicen.",
        body: "El encabezado muestra “Open 24 Hours” y “Open 7 Days a Week”. La sección de contacto vuelve a decir 24 horas. El FAQ publica lunes a sábado de 7:30 a. m. a 9:00 p. m. y domingo de 8:00 a. m. a 5:00 p. m.",
        sources: [{ label: "Comprobar Legacy Fencing", url: "https://yourlegacyfencing.com/" }],
      },
      {
        title: "El español ya es parte de su servicio público.",
        body: "El sitio declara que el equipo bilingüe ofrece servicio completo en inglés y español. Esa promesa permite medir si el recorrido digital y el seguimiento mantienen la misma consistencia.",
        sources: [{ label: "Revisar el sitio oficial", url: "https://yourlegacyfencing.com/" }],
      },
    ],
    unknowns: "Desconozco cuál horario usa hoy el equipo como referencia, cuántas solicitudes llegan fuera de horario y cómo se registran las consultas por idioma.",
    review: "Mediríamos fuente, idioma, hora de contacto, tipo de proyecto, primera respuesta, cotización y siguiente acción. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido desde el primer contacto hasta la cotización, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "in-phaze-electric-029",
    slug: "in-phaze-electric",
    name: "In Phaze Electric",
    contactFirstName: "Tony",
    title: "esto es lo que vi en In Phaze Electric.",
    intro: "In Phaze tiene una reputación pública fuerte y declara que atiende en inglés y español. Revisé el recorrido de una persona que llega al sitio buscando servicio en una ciudad concreta.",
    facts: [
      {
        title: "La página de Winter Garden habla repetidamente de Winter Park.",
        body: "El título y encabezado nombran Winter Garden, pero varias secciones del cuerpo y las preguntas frecuentes hablan de Winter Park. La auditoría encontró un patrón parecido en la página de Lake Mary.",
        sources: [{ label: "Revisar Winter Garden", url: "https://inphazeelectric.com/winter-garden/" }],
      },
      {
        title: "El sitio promete servicio en español, mientras el recorrido web permanece en inglés.",
        body: "La página About declara atención en inglés y español. En la auditoría, la ruta /es/ devolvía 404 y no había selector de idioma en las páginas revisadas.",
        sources: [{ label: "Revisar In Phaze Electric", url: "https://inphazeelectric.com/" }],
      },
    ],
    unknowns: "Desconozco cuánto tráfico reciben esas páginas de ciudad, cuántas solicitudes producen y qué parte de las consultas llega en español.",
    review: "Mediríamos página y ciudad de entrada, idioma, tipo de servicio, primera respuesta, cita y resultado. Así sabríamos qué páginas aportan trabajo real y cuáles necesitan ajuste. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo ese recorrido desde la búsqueda local hasta la solicitud de servicio, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
  {
    id: "cg-auto-center-030",
    slug: "cg-auto-center",
    name: "C & G Auto Center",
    contactFirstName: "Juan",
    title: "esto es lo que vi en C & G Auto Center.",
    intro: "C & G lleva muchos años construyendo confianza alrededor de estimados claros, trato personal y atención en español. Seguí el recorrido público de una persona que intenta saber cuándo puede ir y cómo reservar.",
    facts: [
      {
        title: "El bloque de horarios muestra un mensaje de error.",
        body: "En la auditoría de la página principal y Contacto, el widget dinámico mostraba “Missing business hours data / Error occurred while getting the data”, mientras el horario correcto sí aparecía más abajo.",
        sources: [{ label: "Revisar C & G Auto Center", url: "https://www.cgautocenter.com/" }],
      },
      {
        title: "El botón de cita y la ruta de citas cumplen funciones distintas.",
        body: "El botón principal llevaba a una herramienta externa de check-in de llegada, mientras la página de citas seguía otra ruta. Para alguien que quiere reservar antes de ir, conviene medir cuál camino usa y dónde abandona.",
        sources: [{ label: "Revisar el sitio oficial", url: "https://www.cgautocenter.com/" }],
      },
    ],
    unknowns: "Desconozco si el error de horarios sigue visible en todos los navegadores, cuántas personas usan cada ruta y cómo se registra la solicitud después.",
    review: "Mediríamos página de entrada, idioma, intención, inicio de cita, primera respuesta, cita confirmada y resultado. Cuando los números dicen que todo está funcionando bien, también te lo diré con honestidad.",
    closing: "Si quieres revisar conmigo el recorrido desde que alguien entra al sitio hasta que llega al taller, escríbeme.",
    ctaEvent: "pulso_cta_call",
  },
];
